[package]
name = "leekduck-sync"
version = "0.1.0"
authors = ["Marco Napetti <marco.napetti@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.2"
reqwest = { version = "0.9", default-features = false, features = [ "rustls-tls" ] }
regex = "1.1"
mysql = "16.0"
